### ISSUE TITLE
Fetching repo task history

### ISSUE THREAD

**Issue by linonetwo** [pocket-studios/action-update-version#29]
Run pocket-apps/action-update-version@v1
  with:
    files: package.json, package-lock.json
    version-regexp: \d+.\d+.\d+(\S+)?
    repo-token: ***
    commit-message: ci: update version to v%version%
    spacing-level: 2
Setting input and environment variables
Setting up Octokit and context
Fetching repo task history
Error: Not Found

**Comment by linonetwo** [comment]
```
yml
jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - uses: pocket-apps/action-update-version@v1
      with:
        files: 'package.json'
        version-regexp: '\d+.\d+.\d+(\S+)?'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```
